from parsing.aliyah import Aliyah
from parsing.book import Book
from parsing.chapter import Chapter
from parsing.letter import Letter
from parsing.metadata import *
from parsing.niqud import Niqud
from parsing.parasha import Parasha
from parsing.taam import Taam
from parsing.verse import Verse
from parsing.word import Word
